version: '3.8'

networks:
  cliscles:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.53/32

services:
  pihole:
    image: cbm/pihole:latest
    container_name: pihole
    hostname: pihole
    domainname: cliscles.local
    cap_add:
      - CAP_NET_BIND_SERVICE
      - NET_ADMIN
    networks:
      cliscles:
        ipv4_address: 192.168.1.53
    dns:
      - 1.1.1.2
      - 1.0.0.2
    environment:
      ADMIN_EMAIL: 'cbm@carlesbarreda.cat'
      TZ: 'Europe/Madrid'
      WEBPASSWORD: ''
      DNS1: '1.1.1.2'
      DNS2: '1.0.0.2'
      DNSSEC: 'true'
      DNS_BOGUS_PRIV: 'true'
      ServerIP: '192.168.1.53'
      VIRTUAL_HOST: 'pihole.cliscles.local'
      DNSMASQ_USER: 'pihole'
    volumes:
      - ./config/pihole:/etc/pihole
      - ./config/dnsmasq.d:/etc/dnsmasq.d
      - ./config/dnscrypt-proxy:/etc/dnscrypt-proxy
    restart: unless-stopped
    #restart: always
